# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='hood_admin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='hood_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
