# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gang', '0004_auto_20180528_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gang.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
