# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gang', '0005_auto_20180528_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhood', to='gang.Neighbourhood'),
        ),
    ]
