# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gang', '0012_auto_20180528_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
